import { Toaster } from 'react-hot-toast';
import { AuthProvider } from '@/contexts/AuthContext';
import RootWrapper from "@/components/layout/RootWrapper";
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body>
      <AuthProvider>
        <RootWrapper>{children}</RootWrapper>
        <Toaster />
      </AuthProvider>
      </body>
      </html>
  );
}
