import { DataProvider } from '../contexts/DataContext';
import { AuthProvider } from '../contexts/AuthContext';
import DashboardNav from "@/components/layout/DashboardNav";
import { Toaster } from 'react-hot-toast';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <DashboardNav />
          <DataProvider>{children}</DataProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}